services:
  db:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: itsdb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: itsuser
      MYSQL_PASSWORD: itspass
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"