spring:
  thymeleaf:
    prefix: "file:src/main/resources/templates/"
  datasource:
    url: "jdbc:mysql://localhost:3307/itsdb"
    username: "itsuser"
    password: "itspass"
logging:
  level:
    org.springframework.security: TRACE
